### PR TITLE
Upgrade diesel to latest version

### PR DESCRIPTION
**Pull request by eloyrobillard**
## Description
Upgrade Diesel to 2.1.0.

Also fixes a small linting error in passing.

### Testing Strategy

- [ ] There SHOULD NOT be new errors

### CODE REVIEW

**Review by jhodapp — CHANGES_REQUESTED** [review]
@eloyrobillard Thanks very much for this submission. It doesn't seem to build for me locally and I think the key is in what's being cached or not cached for dependency crates. I'll drop the output from my build here to help you compare to your local build.

I'm running with the following version of Rust:

stable-aarch64-apple-darwin updated - rustc 1.72.0 (5680fa18f 2023-08-23) (from rustc 1.68.2 (9eb3afe9e 2023-03-27))


```sh
eloy-ambi-rs git:(main) cargo build
    Updating crates.io index
  Downloaded async-stream-impl v0.3.5
  Downloaded binascii v0.1.4
  Downloaded tokio-stream v0.1.14
  Downloaded scopeguard v1.2.0
  Downloaded fnv v1.0.7
  Downloaded pin-utils v0.1.0
  Downloaded pear v0.2.7
  Downloaded ppv-lite86 v0.2.17
  Downloaded yansi v1.0.0-rc.1
  Downloaded toml_edit v0.19.15
  Downloaded regex-automata v0.3.8
  Downloaded uncased v0.9.9
  Downloaded try-lock v0.2.4
  Downloaded proc-macro2-diagnostics v0.10.1
  Downloaded log v0.4.20
  Downloaded diesel_derives v1.4.1
  Downloaded futures-channel v0.3.28
  Downloaded atomic v0.5.3
  Downloaded inlinable_string v0.1.15
  Downloaded either v1.9.0
  Downloaded multer v2.1.0
  Downloaded futures-io v0.3.28
  Downloaded tracing-attributes v0.1.26
  Downloaded time-macros v0.2.14
  Downloaded state v0.5.3
  Downloaded ryu v1.0.15
  Downloaded signal-hook-registry v1.4.1
  Downloaded slab v0.4.9
  Downloaded toml v0.7.8
  Downloaded figment v0.10.10
  Downloaded socket2 v0.5.4
  Downloaded tracing-core v0.1.31
  Downloaded diesel_derives v2.1.1
  Downloaded tracing v0.1.37
  Downloaded memchr v2.6.3
  Downloaded http v0.2.9
  Downloaded hashbrown v0.14.0
  Downloaded diesel v1.4.8
  Downloaded syn v1.0.109
  Downloaded rustix v0.38.13
  Downloaded tokio v1.32.0
  Downloaded encoding_rs v0.8.33
  Downloaded libc v0.2.148
  Downloaded diesel v2.1.1
  Downloaded syn v2.0.35
  Downloaded aho-corasick v1.0.5
  Downloaded hyper v0.14.27
  Downloaded regex-syntax v0.7.5
  Downloaded rocket v0.5.0-rc.3
  Downloaded tokio-util v0.7.8
  Downloaded time v0.3.28
  Downloaded mio v0.8.8
  Downloaded serde_json v1.0.107
  Downloaded hashbrown v0.12.3
  Downloaded rocket_codegen v0.5.0-rc.3
  Downloaded rocket_http v0.5.0-rc.3
  Downloaded serde v1.0.188
  Downloaded indexmap v2.0.0
  Downloaded rand v0.8.5
  Downloaded indexmap v1.9.3
  Downloaded proc-macro2 v1.0.67
  Downloaded env_logger v0.10.0
  Downloaded bytes v1.5.0
  Downloaded smallvec v1.11.0
  Downloaded cookie v0.17.0
  Downloaded humantime v2.1.0
  Downloaded once_cell v1.18.0
  Downloaded itoa v1.0.9
  Downloaded getrandom v0.2.10
  Downloaded fastrand v2.0.0
  Downloaded serde_derive v1.0.188
  Downloaded async-trait v0.1.73
  Downloaded termcolor v1.2.0
  Downloaded pear_codegen v0.2.7
  Downloaded lock_api v0.4.10
  Downloaded futures v0.3.28
  Downloaded mime v0.3.17
  Downloaded yansi v0.5.1
  Downloaded tempfile v3.8.0
  Downloaded byteorder v1.4.3
  Downloaded bitflags v1.3.2
  Downloaded rand_chacha v0.3.1
  Downloaded num_cpus v1.16.0
  Downloaded is-terminal v0.4.9
  Downloaded ref-cast v1.0.20
  Downloaded futures-core v0.3.28
  Downloaded scheduled-thread-pool v0.2.7
  Downloaded errno v0.3.3
  Downloaded serde_spanned v0.6.3
  Downloaded devise_codegen v0.4.1
  Downloaded ref-cast-impl v1.0.20
  Downloaded deranged v0.3.8
  Downloaded regex v1.9.5
  Downloaded winnow v0.5.15
  Downloaded h2 v0.3.21
  Downloaded futures-util v0.3.28
  Downloaded time-core v0.1.1
  Downloaded diesel_table_macro_syntax v0.1.0
  Downloaded tower-service v0.3.2
  Downloaded toml_datetime v0.6.3
  Downloaded http-body v0.4.5
  Downloaded cfg-if v1.0.0
  Downloaded autocfg v1.1.0
  Downloaded rocket_sync_db_pools v0.1.0-rc.3
  Downloaded rocket_sync_db_pools_codegen v0.1.0-rc.3
  Downloaded rand_core v0.6.4
  Downloaded devise v0.4.1
  Downloaded quote v1.0.33
  Downloaded bitflags v2.4.0
  Downloaded spin v0.9.8
  Downloaded unicode-ident v1.0.12
  Downloaded parking_lot v0.12.1
  Downloaded stable-pattern v0.1.0
  Downloaded r2d2 v0.8.10
  Downloaded unicode-xid v0.2.4
  Downloaded pin-project-lite v0.2.13
  Downloaded parking_lot_core v0.9.8
  Downloaded tokio-macros v2.1.0
  Downloaded httparse v1.8.0
  Downloaded socket2 v0.4.9
  Downloaded equivalent v1.0.1
  Downloaded pq-sys v0.4.8
  Downloaded percent-encoding v2.3.0
  Downloaded futures-task v0.3.28
  Downloaded async-stream v0.3.5
  Downloaded ubyte v0.10.3
  Downloaded httpdate v1.0.3
  Downloaded glob v0.3.1
  Downloaded want v0.3.1
  Downloaded futures-sink v0.3.28
  Downloaded version_check v0.9.4
  Downloaded devise_core v0.4.1
  Downloaded 132 crates (10.1 MB) in 1.16s (largest was `encoding_rs` at 1.4 MB)
   Compiling proc-macro2 v1.0.67
   Compiling unicode-ident v1.0.12
   Compiling version_check v0.9.4
   Compiling libc v0.2.148
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling pin-project-lite v0.2.13
   Compiling serde v1.0.188
   Compiling itoa v1.0.9
   Compiling memchr v2.6.3
   Compiling futures-channel v0.3.28
   Compiling futures-core v0.3.28
   Compiling proc-macro2-diagnostics v0.10.1
   Compiling bytes v1.5.0
   Compiling pin-utils v0.1.0
   Compiling yansi v1.0.0-rc.1
   Compiling once_cell v1.18.0
   Compiling fnv v1.0.7
   Compiling http v0.2.9
   Compiling tracing-core v0.1.31
   Compiling slab v0.4.9
   Compiling futures-sink v0.3.28
   Compiling futures-task v0.3.28
   Compiling smallvec v1.11.0
   Compiling httparse v1.8.0
   Compiling tracing v0.1.37
   Compiling quote v1.0.33
   Compiling hashbrown v0.12.3
   Compiling syn v2.0.35
   Compiling futures-util v0.3.28
   Compiling mio v0.8.8
   Compiling num_cpus v1.16.0
   Compiling socket2 v0.5.4
   Compiling signal-hook-registry v1.4.1
   Compiling lock_api v0.4.10
   Compiling futures-io v0.3.28
   Compiling time-core v0.1.1
   Compiling parking_lot_core v0.9.8
   Compiling try-lock v0.2.4
   Compiling want v0.3.1
   Compiling time-macros v0.2.14
   Compiling http-body v0.4.5
   Compiling indexmap v1.9.3
   Compiling cookie v0.17.0
   Compiling deranged v0.3.8
   Compiling log v0.4.20
   Compiling httpdate v1.0.3
   Compiling bitflags v2.4.0
   Compiling rustix v0.38.13
   Compiling inlinable_string v0.1.15
   Compiling scopeguard v1.2.0
   Compiling tower-service v0.3.2
   Compiling ref-cast v1.0.20
   Compiling errno v0.3.3
   Compiling uncased v0.9.9
   Compiling equivalent v1.0.1
   Compiling percent-encoding v2.3.0
   Compiling hashbrown v0.14.0
   Compiling tokio v1.32.0
   Compiling time v0.3.28
   Compiling parking_lot v0.12.1
   Compiling indexmap v2.0.0
   Compiling getrandom v0.2.10
   Compiling socket2 v0.4.9
   Compiling stable-pattern v0.1.0
   Compiling pq-sys v0.4.8
   Compiling winnow v0.5.15
   Compiling state v0.5.3
   Compiling either v1.9.0
   Compiling futures v0.3.28
   Compiling rand_core v0.6.4
   Compiling devise_core v0.4.1
   Compiling figment v0.10.10
   Compiling hyper v0.14.27
   Compiling multer v2.1.0
   Compiling async-trait v0.1.73
   Compiling ppv-lite86 v0.2.17
   Compiling serde_json v1.0.107
   Compiling syn v1.0.109
   Compiling rand_chacha v0.3.1
   Compiling is-terminal v0.4.9
   Compiling diesel_table_macro_syntax v0.1.0
   Compiling scheduled-thread-pool v0.2.7
   Compiling aho-corasick v1.0.5
   Compiling rocket v0.5.0-rc.3
   Compiling encoding_rs v0.8.33
   Compiling glob v0.3.1
   Compiling spin v0.9.8
   Compiling unicode-xid v0.2.4
   Compiling regex-syntax v0.7.5
   Compiling mime v0.3.17
   Compiling byteorder v1.4.3
   Compiling serde_derive v1.0.188
   Compiling tokio-macros v2.1.0
   Compiling pear_codegen v0.2.7
   Compiling ref-cast-impl v1.0.20
   Compiling devise_codegen v0.4.1
   Compiling async-stream-impl v0.3.5
   Compiling pear v0.2.7
   Compiling devise v0.4.1
   Compiling fastrand v2.0.0
   Compiling ryu v1.0.15
   Compiling async-stream v0.3.5
   Compiling tempfile v3.8.0
   Compiling rocket_http v0.5.0-rc.3
   Compiling regex-automata v0.3.8
   Compiling diesel_derives v2.1.1
   Compiling r2d2 v0.8.10
   Compiling rand v0.8.5
   Compiling rocket_sync_db_pools v0.1.0-rc.3
   Compiling atomic v0.5.3
   Compiling yansi v0.5.1
   Compiling binascii v0.1.4
   Compiling rocket_sync_db_pools_codegen v0.1.0-rc.3
   Compiling humantime v2.1.0
   Compiling regex v1.9.5
   Compiling termcolor v1.2.0
   Compiling rocket_codegen v0.5.0-rc.3
   Compiling bitflags v1.3.2
   Compiling env_logger v0.10.0
   Compiling tokio-util v0.7.8
   Compiling tokio-stream v0.1.14
   Compiling serde_spanned v0.6.3
   Compiling toml_datetime v0.6.3
   Compiling toml_edit v0.19.15
   Compiling ubyte v0.10.3
   Compiling diesel v2.1.1
   Compiling diesel_derives v1.4.1
   Compiling h2 v0.3.21
   Compiling toml v0.7.8
   Compiling diesel v1.4.8
   Compiling ambi-rs v0.1.0 (/Users/jhodapp/Projects/rust/eloy-ambi-rs)
error[E0277]: the trait bound `diesel::PgConnection: Poolable` is not satisfied
  --> src/lib.rs:23:25
   |
23 | pub struct PgConnection(diesel::PgConnection);
   |                         ^^^^^^ the trait `Poolable` is not implemented for `diesel::PgConnection`
   |
   = help: the trait `Poolable` is implemented for `rocket_sync_db_pools::diesel::PgConnection`
note: required by a bound in `rocket_sync_db_pools::Connection`
  --> /Users/jhodapp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rocket_sync_db_pools-0.1.0-rc.3/src/connection.rs:44:29
   |
44 | pub struct Connection<K, C: Poolable> {
   |                             ^^^^^^^^ required by this bound in `Connection`

error[E0277]: the trait bound `diesel::PgConnection: Poolable` is not satisfied
  --> src/lib.rs:23:25
   |
23 | pub struct PgConnection(diesel::PgConnection);
   |                         ^^^^^^ the trait `Poolable` is not implemented for `diesel::PgConnection`
   |
   = help: the trait `Poolable` is implemented for `rocket_sync_db_pools::diesel::PgConnection`
note: required by a bound in `ConnectionPool`
  --> /Users/jhodapp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rocket_sync_db_pools-0.1.0-rc.3/src/connection.rs:20:33
   |
20 | pub struct ConnectionPool<K, C: Poolable> {
   |                                 ^^^^^^^^ required by this bound in `ConnectionPool`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `ambi-rs` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by eloyrobillard** [comment]
It looks like I forgot to update the `main` branch of my fork, so it was still building diesel v1.4.8, hence the error.

I updated it so it should be fine now.

**Review by jhodapp — CHANGES_REQUESTED** [review]
Builds cleanly for me now, however it prints a warning about the proper table definition macro to use that I think is worth cleaning up with this upgrade.

Otherwise, seems to function normally with ambi_mock_client

**Comment by eloyrobillard** [comment]
Ok, removed the warning

**Review by jhodapp — APPROVED** [review]
Looks great, functions as expected. Thanks for this contribution Eloy!

**Pull request merged**
